[profile.default]
solc = '0.8.23'
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 3
optimizer = false
via_ir = false
evm_version = 'paris'

[fuzz]
runs = 100

[profile.optimized]
optimizer = true
optimizer_runs = 4_294_967_295
via_ir = true
out = 'optimized-out'

[profile.intense.fuzz]
runs = 10000
